services:

  database:
    image: postgres:18.0-alpine
    container_name: local-stack-db-itmentorcommunityplatform
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: it_mentor_community_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    restart: unless-stopped

  gateway:
    image: ghcr.io/it-mentor-community-platform/gateway/gateway:dev
    container_name: local-stack-gateway-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8080:8080"
    restart: unless-stopped

  data-importer:
    image: ghcr.io/it-mentor-community-platform/data-importer/data-importer:dev
    container_name: local-stack-dataimporter-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    ports:
      - "8082:8080"
    restart: unless-stopped

  auth-service:
    image: ghcr.io/it-mentor-community-platform/auth-service/auth-service:dev
    container_name: local-stack-auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: local-stack-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.0
    container_name: local-stack-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
      
  profile-service:
    image: ghcr.io/it-mentor-community-platform/profile-service/profile-service:dev
    container_name: local-stack-profile-service-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8083:8080"
    restart: unless-stopped

  project-service:
    image: ghcr.io/it-mentor-community-platform/project-service/project-service:dev
    container_name: local-stack-project-service-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8084:8080"
    restart: unless-stopped

  mentor-service:
    image: ghcr.io/it-mentor-community-platform/mentor-service/mentor-service:dev
    container_name: local-stack-mentor-service
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8085:8080"
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: local-stack-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: >
        PLAINTEXT_INTERNAL://0.0.0.0:9092,
        PLAINTEXT_EXTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT_INTERNAL://kafka:9092,
        PLAINTEXT_EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT_INTERNAL:PLAINTEXT,
        PLAINTEXT_EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CLUSTER_ID: "YWJhY2RlZmdoaWprbG1u"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: local-stack-kafka-ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

volumes:
  postgres_data:
    name: local-stack-postgres-data-itmentorcommunityplatform