services:

  database:
    image: postgres:18.0-alpine
    container_name: local-stack-db-itmentorcommunityplatform
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: it_mentor_community_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  gateway:
    image: ghcr.io/it-mentor-community-platform/gateway/gateway:dev
    container_name: local-stack-gateway-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8080:8080"
    restart: unless-stopped

  data-importer:
    image: ghcr.io/it-mentor-community-platform/data-importer/data-importer:dev
    container_name: local-stack-dataimporter-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    ports:
      - "8082:8080"
    restart: unless-stopped

  auth-service:
    image: ghcr.io/it-mentor-community-platform/auth-service/auth-service:dev
    container_name: local-stack-auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: local-stack-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.0
    container_name: local-stack-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
      
  profile-service:
    image: ghcr.io/it-mentor-community-platform/profile-service/profile-service:dev
    container_name: local-stack-profile-service-itmentorcommunityplatform
    environment:
      - SPRING_PROFILES_ACTIVE=local-stack
    ports:
      - "8083:8080"
    restart: unless-stopped

volumes:
  postgres_data:
    name: local-stack-postgres-data-itmentorcommunityplatform