global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'prometheus'
      password: 'password'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'data-importer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['data-importer:8080']

  - job_name: 'mentor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'mentor-service:8080' ]

  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profile-service:8080']

  - job_name: 'project-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['project-service:8080']

  - job_name: 'job-market-analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job-market-analytics-service:8080' ]