apiVersion: 1

datasources:
  - name: Postgresql_datasource
    type: postgres
    uid: GhzMNppVk
    url: local-stack-db-itmentorcommunityplatform:5432
    user: root
    secureJsonData:
      password: password
    jsonData:
      database: it_mentor_community_platform
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1800
      timescaledb: false