{
 "title": "custom_metrics_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "profile-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"profile-service\", __name__=~\"profile_service_get_profile_success_total|profile_service_get_profile_error_total|profile_service_get_profile_duration_seconds_(count|sum|max)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "project-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"project-service\", __name__=~\"projects_created_frontend_total|projects_created_telegram_bot_total|projects_created_data_importer_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "job-market-analytics-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"job-market-analytics-service\", __name__=~\"hh_api_requests_failed_total|search_queries_requests\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data_importer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"data-importer\", __name__=~\"data_importer_users_success_total|data_importer_users_error_total|data_importer_profiles_success_total|data_importer_profiles_error_total|data_importer_projects_success_total|data_importer_projects_error_total|data_importer_users_import_duration_seconds_count|data_importer_users_import_duration_seconds_sum|data_importer_users_import_duration_seconds_max|data_importer_profiles_import_duration_seconds_count|data_importer_profiles_import_duration_seconds_sum|data_importer_profiles_import_duration_seconds_max|data_importer_projects_import_duration_seconds_count|data_importer_projects_import_duration_seconds_sum|data_importer_projects_import_duration_seconds_max\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}