{
 "title": "job_market_analytic_service_metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average salary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(avg_salary) AS \"avg_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    created_at BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 2\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    },
    {
     "title": "Median salary ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(median_salary_mid) AS \"median_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    created_at BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 2\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    },
    {
     "title": "Vacancy count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(vacancy_count) AS \"median_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    snapshot_date BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 2\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Java",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average salary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(avg_salary) AS \"avg_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    created_at BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 1\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    },
    {
     "title": "Median salary ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(median_salary_mid) AS \"median_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    created_at BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 1\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    },
    {
     "title": "Vacancy count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "dataset": "db_main",
       "rawSql": "SELECT \r\n    $__timeGroup(created_at, '1d') AS time,\r\n    AVG(vacancy_count) AS \"median_salary\"\r\nFROM \r\n    job_market_analytics_service_staging.market_data_points \r\nWHERE \r\n    snapshot_date BETWEEN '2026-07-22 00:00:00' AND '2026-08-22 23:59:59'\r\n    AND search_query_id = 1\r\nGROUP BY \r\n    1\r\nORDER BY \r\n    1;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Failure sheduled jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "db_main",
     "rawSql": "SELECT COUNT(*) \r\nFROM job_market_analytics_service_staging.hh_scheduled_jobs \r\nWHERE snapshot_date BETWEEN '2026-07-22' AND '2026-08-22'\r\nAND status != 'DONE'"
    }
   ]
  }
 ]
}