{
 "title": "labor_market_analytics_metrics_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HH Api requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n    increase(\r\n        hh_api_requests_total{\r\n            job=\"job-market-analytics-service\"\r\n        }[$__interval]\r\n    )\r\n )",
     "legendFormat": "HH Api Requests"
    }
   ]
  },
  {
   "title": "HH Api requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(\r\n        hh_api_requests_total{\r\n            job=\"job-market-analytics-service\",\r\n            status=\"success\"\r\n        }[$__interval]\r\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(\r\n        hh_api_requests_total{\r\n            job=\"job-market-analytics-service\",\r\n            status=\"error\"\r\n        }[$__interval]\r\n)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Created search queries total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "search_queries_created_count{\r\n    job=\"job-market-analytics-service\"\r\n }",
     "legendFormat": "Created queries"
    }
   ]
  }
 ]
}